/* include/config1.h.  Generated automatically by configure.  */
/* Soundcard configuration for ALSA driver */
/* Copyright (c) by Anders Semb Hermansen <ahermans@vf.telia.no>, */
/*                  Jaroslav Kysela <perex@suse.cz> */

#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_SERIAL_U16550_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#define CONFIG_SND_MPU401_MODULE 1
#define CONFIG_SND_ALS100_MODULE 1
#define CONFIG_SND_AZT2320_MODULE 1
#define CONFIG_SND_CMI8330_MODULE 1
#define CONFIG_SND_DT019X_MODULE 1
#define CONFIG_SND_ES18XX_MODULE 1
#define CONFIG_SND_OPL3SA2_MODULE 1
#define CONFIG_SND_SGALAXY_MODULE 1
#define CONFIG_SND_SSCAPE_MODULE 1
#define CONFIG_SND_AD1816A_MODULE 1
#define CONFIG_SND_AD1848_MODULE 1
#define CONFIG_SND_CS4231_MODULE 1
#define CONFIG_SND_CS4232_MODULE 1
#define CONFIG_SND_CS4236_MODULE 1
/* #undef CONFIG_SND_PC98_CS4232_MODULE */
#define CONFIG_SND_ES1688_MODULE 1
#define CONFIG_SND_GUSCLASSIC_MODULE 1
#define CONFIG_SND_GUSMAX_MODULE 1
#define CONFIG_SND_GUSEXTREME_MODULE 1
#define CONFIG_SND_INTERWAVE_MODULE 1
#define CONFIG_SND_INTERWAVE_STB_MODULE 1
#define CONFIG_SND_OPTI92X_AD1848_MODULE 1
#define CONFIG_SND_OPTI92X_CS4231_MODULE 1
#define CONFIG_SND_OPTI93X_MODULE 1
#define CONFIG_SND_SB8_MODULE 1
#define CONFIG_SND_SB16_MODULE 1
#define CONFIG_SND_SBAWE_MODULE 1
#define CONFIG_SND_ES968_MODULE 1
#define CONFIG_SND_WAVEFRONT_MODULE 1
#define CONFIG_SND_ALS4000_MODULE 1
#define CONFIG_SND_AZT3328_MODULE 1
#define CONFIG_SND_CMIPCI_MODULE 1
#define CONFIG_SND_CS4281_MODULE 1
#define CONFIG_SND_ENS1370_MODULE 1
#define CONFIG_SND_ENS1371_MODULE 1
#define CONFIG_SND_ES1938_MODULE 1
#define CONFIG_SND_ES1968_MODULE 1
#define CONFIG_SND_FM801_MODULE 1
#define CONFIG_SND_INTEL8X0_MODULE 1
#define CONFIG_SND_MAESTRO3_MODULE 1
#define CONFIG_SND_RME32_MODULE 1
#define CONFIG_SND_RME96_MODULE 1
#define CONFIG_SND_SONICVIBES_MODULE 1
#define CONFIG_SND_VIA82XX_MODULE 1
#define CONFIG_SND_ALI5451_MODULE 1
#define CONFIG_SND_CS46XX_MODULE 1
#define CONFIG_SND_EMU10K1_MODULE 1
#define CONFIG_SND_ICE1712_MODULE 1
#define CONFIG_SND_ICE1724_MODULE 1
#define CONFIG_SND_KORG1212_MODULE 1
#define CONFIG_SND_NM256_MODULE 1
#define CONFIG_SND_RME9652_MODULE 1
#define CONFIG_SND_HDSP_MODULE 1
#define CONFIG_SND_TRIDENT_MODULE 1
#define CONFIG_SND_VX222_MODULE 1
#define CONFIG_SND_YMFPCI_MODULE 1
/* #undef CONFIG_SND_POWERMAC_MODULE */
/* #undef CONFIG_SND_SA11XX_UDA1341_MODULE */
#define CONFIG_SND_USB_AUDIO_MODULE 1
/* #undef CONFIG_SND_HARMONY_MODULE */
#define CONFIG_SND_VXPOCKET_MODULE 1
#define CONFIG_SND_VXP440_MODULE 1
#define CONFIG_SND_SERIALMIDI_MODULE 1
#define CONFIG_SND_PDPLUS_MODULE 1
#define CONFIG_SND_MSND_PINNACLE_MODULE 1
#define CONFIG_SND_PDAUDIOCF_MODULE 1
